# Generated by Django 4.1.6 on 2023-02-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='amir', max_length=32)),
                ('age', models.IntegerField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
