# Generated by Django 4.1.6 on 2023-02-10 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='عنوان سوال')),
                ('slug', models.SlugField(max_length=24)),
                ('body', models.CharField(max_length=120)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userquestion', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مورد نظر')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bode', models.CharField(max_length=120)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useranswer', to=settings.AUTH_USER_MODEL)),
                ('whitch_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitch_answer', to='home.question')),
            ],
        ),
    ]
